Repository hestiaAI/hestialabs-experiences, pull requests merged in 2021-11, with the labels that each got.

#186 feat: Added experience card point to the extension repository
  components/TheDataExperienceList.vue
  config/config.json
  config/workshop.json
  manifests/experiences/ad-radar/ad-radar.json
  manifests/experiences/ad-radar/examples/main/useless.yaml
  manifests/experiences/ad-radar/index.js
  manifests/icons/eyeballs.jpg
  manifests/index.js
  pages/index.vue
Labels: enhancement

#204 Fixed file tree in UnitFileViewer
  components/UnitCsvViewer.vue
  components/UnitFileExplorer.vue
  components/UnitJsonViewer.vue
  utils/file.js
Labels: bug, refactoring

#207 refactor: Unified file extraction logic for all pipelines and use cases
  components/BaseDataDownloadButton.vue
  components/TheDataExperience.vue
  components/TheDataExperienceDefault.vue
  components/TheFilesCombobox.vue
  components/TheSampleSelector.vue
  components/TheTableFilter.vue
  components/UnitCsvViewer.vue
  components/UnitCustomPipeline.vue
  components/UnitFileExplorer.vue
  components/UnitFiles.vue
  components/UnitFilterableTable.vue
  components/UnitHtmlViewer.vue
  components/UnitImageViewer.vue
  components/UnitJsonViewer.vue
  components/UnitPdfViewer.vue
  components/UnitQuery.vue
  components/UnitTextViewer.vue
  manifests/experiences/facebook/facebook.json
  manifests/experiences/tinder/tinder.json
  manifests/experiences/tracker-control/pipeline.js
  manifests/experiences/tracker-control/tracker-control.json
  manifests/experiences/twitter/pipeline.js
  manifests/experiences/twitter/twitter.json
  manifests/experiences/uber/pipeline.js
  manifests/index.js
  manifests/preprocessors.js
  pages/import.vue
  utils/csv.js
  utils/file-manager.js
  utils/file-reader.js
  utils/file.js
  utils/json.js
  utils/process-files.js
  utils/rdf.js
  utils/unzip.js
Labels: enhancement, performance, refactoring

#216 feat: separated data experiences and refactored code
  components/CardOrItemList.vue
  components/TheAppBar.vue
  components/TheDataExperienceList.vue
  config/config.json
  config/workshop.json
  layouts/default.vue
  manifests/experiences/amazon/amazon.json
  manifests/experiences/apple/apple.json
  manifests/experiences/google/google.json
  manifests/experiences/other/examples/main/useless.yaml
  manifests/experiences/other/index.js
  manifests/experiences/other/other.json
  manifests/experiences/spotify/spotify.json
  manifests/experiences/youtube/youtube.json
  manifests/icons/help.png
  pages/index.vue
Labels: enhancement, refactoring

#214 feat: Kepler integration
  components/TheDataExperienceDefault.vue
  components/UnitConsentForm.vue
  components/UnitCsvViewer.vue
  components/UnitCustomPipeline.vue
  components/UnitFilterableTable.vue
  components/UnitIframe.vue
  components/UnitQuery.vue
  components/UnitVegaViz.vue
  components/graphs/TrackerGraph.vue
  components/graphs/TwitterOverview.vue
  components/graphs/UberOverview.vue
  components/graphs/VueGraphByName.vue
  config/config.json
  manifests/csv-processors.js
  manifests/experiences/twitter/pipeline.js
  manifests/experiences/uber-kepler/examples/main/uber.yml
  manifests/experiences/uber-kepler/index.js
  manifests/experiences/uber-kepler/pipeline.js
  manifests/experiences/uber-kepler/uber-kepler.json
  pages/import.vue
  static/kepler/index.html
  static/kepler/kepler-init.js
Labels: enhancement, refactoring

#244 fix: unitvegaviz and chartview dont crash when theres no data
  components/chart/ChartView.vue
  components/unit/UnitVegaViz.vue
Labels: bug, help wanted

#253 fix: csv reader handles errors correctly, works with duplicated columns
  utils/csv.js
Labels: bug

#261 performance: (jsonviewer) lists are now split into groups of 50 elements
  utils/json.js
Labels: performance
